### ISSUE TITLE
生成的json可以按struct的字段顺序来排序么?

### ISSUE THREAD

**Issue by Liloupar** [Enokiy/go-struct-to-json-intellij-plugin#1]

**Comment by Enokiy** [comment]
谢谢关注，您是在什么场景下觉得结果字段排序是有必要的呢？我个人暂时没有结果字段排序的需求，参考下您的业务场景，有需求的化后续可以考虑；

**Comment by Liloupar** [comment]
> 谢谢关注，您是在什么场景下觉得结果字段排序是有必要的呢？我个人暂时没有结果字段排序的需求，参考下您的业务场景，有需求的化后续可以考虑；

感谢你的回复, 我只是觉得和struct的字段顺序保持一致比较好看. 我自己简单的处理了一下解决了.
只需要把 hashmap 改为 linkedhashmap 即可保持顺序.
